server:
  port: 8001

spring:
  config:
    use-legacy-processing: true
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: cartisan-mall-goods
  profiles:
    include: web, mysql
    active: local

cartisan:
  jwt:
    key: cartisan-jwt
    ttl: 1800000
  info:
    title: Cartisan mall
    serviceUrl: http://www.cartisan.com
    version: 1.0
    contact:
      name: colin
      url: zhang_colin.github.com
      email: zhang_colin@163.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
