### 搜索相册
GET http://{{host}}:{{port}}/albums/search?title=华
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取相册
GET http://{{host}}:{{port}}/albums/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取相册图片
GET http://{{host}}:{{port}}/albums/1/images
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加相册
POST http://{{host}}:{{port}}/albums
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "title": "生鲜",
  "coverImage": "",
  "description": "",
  "sequence": 0
}

### 编辑相册
PUT http://{{host}}:{{port}}/albums/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "title": "",
  "coverImage": "",
  "description": "",
  "sequence": 0
}

### 添加相册图片
PUT http://{{host}}:{{port}}/albums/1/addImage?imageUrl=http://localhost:9000/cartisan-mall/1594960287235047424/WechatIMG497.jpeg
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}


### 删除相册图片
PUT http://{{host}}:{{port}}/albums/1/removeImage?imageUrl=http://localhost:9000/cartisan-mall/1594960287235047424/WechatIMG497.jpeg
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 删除相册
DELETE http://{{host}}:{{port}}/albums/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
