server:
  port: 8081
#  servlet:
#    context-path: /pay

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: pay
  profiles:
    include: web, mysql
    active: local
  freemarker:
#    template-loader-path: classpath:/templates
#    cache: false
#    charset: utf-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: request
    suffix: .ftl

mybatis:
  configuration:
    map-underscore-to-camel-case: true

cartisan:
  jwt:
    key: cartisan-jwt
    ttl: 1800000
  info:
    title: Cartisan mall
    serviceUrl: http://www.cartisan.com
    version: 1.0
    contact:
      name: colin
      url: zhang_colin.github.com
      email: zhang_colin@163.com
  security:
    ignored:
      urls: # 安全路由白名单
        - /
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        - /**/v2/api-docs/**
        - /**/v2/api-docs-ext/**
        - /**/*.png
        - /**/*.ico
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /system/login
        - /interface-ui/**
        - /api/**
#        - /admin/register

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


