### 搜索SKU
GET http://{{host}}:{{port}}/skus/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取SKU
GET http://{{host}}:{{port}}/skus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加SKU
POST http://{{host}}:{{port}}/skus
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "spuId": "",
  "sn": "",
  "name": "",
  "specification": "",
  "price": "",
  "weight": "",
  "quantity": "",
  "alertQuantity": "",
  "image": "",
  "images": ""
}

### 编辑SKU
PUT http://{{host}}:{{port}}/skus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "spuId": "",
  "sn": "",
  "name": "",
  "specification": "",
  "price": "",
  "weight": "",
  "quantity": "",
  "alertQuantity": "",
  "image": "",
  "images": ""
}

### 删除SKU
DELETE http://{{host}}:{{port}}/skus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
