### 获取分类树
GET http://{{host}}:{{port}}/categories/tree
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取商品分类）
GET http://{{host}}:{{port}}/categories/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加商品分类
POST http://{{host}}:{{port}}/categories
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "parentId": 0,
  "name": "宠物",
  "isShow": false,
  "isMenu": false
}

### 编辑商品分类
PUT http://{{host}}:{{port}}/categories/1183
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "parentId": 0,
  "name": "图书、音像、电子书刊111",
  "isShow": false,
  "isMenu": false
}

### 移动商品分类
POST http://{{host}}:{{port}}/categories/moveCategories
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

[{
  "id": 3,
  "parentId": 2,
  "sequence": 0
}, {
  "id": 4,
  "parentId": 2,
  "sequence": 1
}]


### 删除商品分类
DELETE http://{{host}}:{{port}}/categories/1183
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
