### 获取品牌的所有分类关联
GET http://{{host}}:{{port}}/brandCategories/brand/1115
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取分类的所有品牌关联
GET http://{{host}}:{{port}}/brandCategories/category/3
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加品牌
POST http://{{host}}:{{port}}/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "Cartisan",
  "logo": "http://mall.cartisan.com",
  "firstLetter": "C",
  "description": "Colin自创品牌",
  "sequence": 10
}

### 编辑品牌
PUT http://{{host}}:{{port}}/brands/325401
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "Cartisan",
  "logo": "http://mall.cartisan.com/logo.png",
  "firstLetter": "C",
  "description": "Colin自创知名品牌",
  "sequence": 10
}

### 添加分类
PUT http://{{host}}:{{port}}/brands/1115/addCategory?categoryId=3
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 移除分类
PUT http://{{host}}:{{port}}/brands/1115/removeCategory?categoryId=3
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 删除品牌
DELETE http://{{host}}:{{port}}/brands/325401
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
