### 搜索品牌
GET http://{{host}}:{{port}}/brands/search?name=TC&letter=H&page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取所有品牌
GET http://{{host}}:{{port}}/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取品牌
GET http://{{host}}:{{port}}/brands/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加品牌
POST http://{{host}}:{{port}}/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "",
  "image": "",
  "letter": "",
  "sequence": ""
}

### 编辑品牌
PUT http://{{host}}:{{port}}/brands/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "",
  "image": "",
  "letter": "",
  "sequence": ""
}

### 删除品牌
DELETE http://{{host}}:{{port}}/brands/325413
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
