### 搜索品牌
GET http://{{host}}:{{port}}/brands/search?name=TC&letter=H&page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取所有品牌
GET http://{{host}}:{{port}}/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取品牌
GET http://{{host}}:{{port}}/brands/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加品牌
POST http://{{host}}:{{port}}/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "Cartisan",
  "image": "Cartisan",
  "letter": "C",
  "sequence": 10
}

### 编辑品牌
PUT http://{{host}}:{{port}}/brands/325401
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "Cartisan1",
  "image": "Cartisan1",
  "letter": "C",
  "sequence": 20
}

### 删除品牌
DELETE http://{{host}}:{{port}}/brands/325401
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
