### 搜索活动
GET http://{{host}}:{{port}}/activities/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取活动
GET http://{{host}}:{{port}}/activities/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加活动
POST http://{{host}}:{{port}}/activities
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "title": "",
  "start": "",
  "end": "",
  "content": "",
  "status": ""
}

### 编辑活动
PUT http://{{host}}:{{port}}/activities/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "title": "",
  "start": "",
  "end": "",
  "content": "",
  "status": ""
}

### 删除活动
DELETE http://{{host}}:{{port}}/activities/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
