### 获取所有退货原因
GET http://{{host}}:{{port}}/returnCauses
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取退货原因
GET http://{{host}}:{{port}}/returnCauses/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加退货原因
POST http://{{host}}:{{port}}/returnCauses
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "cause": "包装破损",
  "enable": true,
  "sequence": 10
}

### 编辑退货原因
PUT http://{{host}}:{{port}}/returnCauses/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{

  "cause": "",
  "enable": "",
  "sequence": ""
}

### 删除退货原因
DELETE http://{{host}}:{{port}}/returnCauses/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
