server:
  port: 7001
spring:
  application:
    name: cartisan-mall-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: cartisan_mall_goods_route
          uri: lb://cartisan-mall-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1

        - id: cartisan_mall_system_route
          uri: lb://cartisan-mall-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
