### 搜索规格
GET http://{{host}}:{{port}}/specifications/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取规格
GET http://{{host}}:{{port}}/specifications/39
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加规格
POST http://{{host}}:{{port}}/specifications
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "templateId": "42",
  "name": "型号",
  "options": "A,B,C",
  "sequence": "10"
}

### 编辑规格
PUT http://{{host}}:{{port}}/specifications/40
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "templateId": "42",
  "name": "型号",
  "options": "A,B,C",
  "sequence": "20"
}

### 删除规格
DELETE http://{{host}}:{{port}}/specifications/40
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
