### 获取模板下所有的规格
GET http://{{host}}:{{port}}/specifications?templateId=42
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加规格
POST http://{{host}}:{{port}}/specifications
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "templateId": "",
  "name": "",
  "options": [],
  "sequence": 0
}

### 编辑规格
PUT http://{{host}}:{{port}}/specifications/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "templateId": "",
  "name": "",
  "options": [],
  "sequence": 0
}

### 删除规格
DELETE http://{{host}}:{{port}}/specifications/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
