### 搜索模板
GET http://{{host}}:{{port}}/templates/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取模板
GET http://{{host}}:{{port}}/templates/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加模板
POST http://{{host}}:{{port}}/templates
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "name": ""
}

### 编辑模板
PUT http://{{host}}:{{port}}/templates/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "name": ""
}

### 删除模板
DELETE http://{{host}}:{{port}}/templates/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
