### 搜索SPU
GET http://{{host}}:{{port}}/spus/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取SPU
GET http://{{host}}:{{port}}/spus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加SPU
POST http://{{host}}:{{port}}/spus
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "sn": "A001",
  "name": "非常好货 {颜色} {版本}",
  "caption": "非常好货副标题",
  "brandId": 1115,
  "category1Id": 1,
  "category2Id": 2,
  "category3Id": 3,
  "templateId": 42,
  "image": "",
  "images": "",
  "saleService": "",
  "introduction": "非常好货",
  "specificationItems": "{\"颜色\":[\"黑色\",\"蓝色\"],\"版本\":[\"6GB+64GB\"]}",
  "parameterItems": ""
}

### 编辑SPU
PUT http://{{host}}:{{port}}/spus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{

  "sn": "",
  "name": "",
  "caption": "",
  "brandId": "",
  "category1Id": "",
  "category2Id": "",
  "category3Id": "",
  "templateId": "",
  "image": "",
  "images": "",
  "saleService": "",
  "introduction": "",
  "specificationItems": "",
  "parameterItems": "",
  "isMarketable": "",
  "enableSpecification": "",
  "auditStatus": ""
}

### 删除SPU
DELETE http://{{host}}:{{port}}/spus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
