### 搜索商品日志
GET http://{{host}}:{{port}}/spuLogs/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取商品日志
GET http://{{host}}:{{port}}/spuLogs/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加商品日志
POST http://{{host}}:{{port}}/spuLogs
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "spuId": "",
  "content": "",
  "operator": ""
}

### 编辑商品日志
PUT http://{{host}}:{{port}}/spuLogs/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  
  "spuId": "",
  "content": "",
  "operator": ""
}

### 删除商品日志
DELETE http://{{host}}:{{port}}/spuLogs/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
